---
- name: deploy vsftpd
  hosts: ansible-01
  tasks:
    - name: install vsftpd
      yum: name=vsftpd
    - name: enable vsftpd
      service: name=vsftpd enabled=true
    - name: created readme file
      copy:
        content: "test message"
        dest: "/var/ftp/pub/README"
        force: no
        mode: 0444